apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blog.name" . }}-nginx-vhost
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "blog.name" . }}-nginx-vhost
    chart: {{ template "blog.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
  {{- end }}
data:
  nginx.conf: |-
    server {
        listen {{ .Values.nginxService.internalPort }};
        listen [::]:{{ .Values.nginxService.internalPort }};

        server_name {{ .Values.nginxService.host }};
        root /var/www/blog/public;
        index index.php index.html index.htm;

        location / {
             try_files $uri /index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        access_log /dev/stdout;
        error_log /dev/stderr;
    }
