apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "fullname" . }}-pv
  labels:
    type: local
    pv: {{ template "fullname" . }}-pv
spec:
  {{ include "storageClass" . }}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var"
    type: DirectoryOrCreate