apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "fullname" . }}-pv
  labels:
    type: local
    pv: {{ template "fullname" . }}-pv
spec:
  {{ include "storageClass" . }}
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var"