{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end -}}