apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-blog
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.blogService.type }}
  ports:
  - port: {{ .Values.blogService.blogPort }}
    targetPort: {{ .Values.blogService.blogPort }}
    protocol: TCP
    name: {{ .Values.blogService.name }}
  selector:
    app: {{ template "fullname" . }}-blog
