kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: blog-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
parameters:
  archiveOnDelete: "false"