# Default values for david You.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  compatibility:
    openshift:
      adaptSecurityContext: auto
nameOverride: ""
replicaCount: 1
image:
  registry: hub.docker.com
  repository: tianya2022/laravel-blog
  tag: latest
  pullPolicy: IfNotPresent
nginxService:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  docRoot: /var/www/blog/public
blogService:
  name: blog
  type: ClusterIP
  blogPort: 9000
  indexFile: index.php
persistence:
  enabled: false
  storageClass: hostpath
  accessMode: ReadWriteMany
  size: 3Gi
  existingClaim: ""
externalDatabase:
  existingSecret: ""
  host: "localhost"
  port: 3306
  user: laravel
  password: "laravel"
  database: laravel
mariadb:
  enabled: true
  replication:
    enabled: false
  db:
    name: laravel
    user: laravel
    password: laravel
  master:
    persistence:
      enabled: false
      # storageClass: "-"
      accessModes:
        - ReadWriteOnce
      size: 2Gi
ingress:
  enabled: true
  hosts:
    - "blog.test.com"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
  - hosts:
    - blog.test.com
    secretName: blog-app-www-dev-tls
resources:
  limits:
    cpu: 120m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi
extraEnv:
